Repository validator-labs/validator-plugin-aws, pull requests merged in 2024-11, with the labels that each got.

#501 feat: support inline auth
  Dockerfile
  Dockerfile.devspace
  README.md
  api/v1alpha1/awsvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-aws/crds/validation.spectrocloud.labs_awsvalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_awsvalidators.yaml
  config/samples/awsvalidator-inline-auth.yaml
  go.mod
  internal/controller/awsvalidator_controller.go
  internal/controller/awsvalidator_controller_test.go
Labels: size:L, lgtm, new-feature

#482 chore(main): release 0.1.8
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: documentation, autorelease: pending, size:M

#520 fix: make inline auth work in direct mode too
  api/v1alpha1/awsvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-aws/crds/validation.spectrocloud.labs_awsvalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_awsvalidators.yaml
  go.mod
  internal/controller/awsvalidator_controller.go
  internal/controller/awsvalidator_controller_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: bug, size:XL

#513 chore(main): release 0.1.9
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:S

#524 chore(main): release 0.1.10
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:S
