Repository validator-labs/validator-plugin-aws, pull requests merged in 2024-07, with the labels that each got.

#412 chore(main): release 0.1.1
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending

#432 chore: switch to using common package for str utils
  go.mod
  go.sum
  internal/utils/strings/strings.go
  internal/utils/strings/strings_test.go
  internal/validators/ami/ami_validator.go
  internal/validators/iam/iam_validator.go
  internal/validators/servicequota/servicequota_validator.go
  internal/validators/tag/tag_validator.go
Labels: size:L, lgtm

#443 ci: add reviewable-ext make target to update chart crds
  Makefile
  chart/validator-plugin-aws/crds/validation.spectrocloud.labs_awsvalidators.yaml
Labels: enhancement, size:M, lgtm

#445 chore: update generated files
  api/v1alpha1/zz_generated.deepcopy.go
Labels: size:S, lgtm

#423 chore(main): release 0.1.2
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:M, lgtm
