Repository validator-labs/validator-plugin-aws, pull requests merged in 2024-08, with the labels that each got.

#450 refactor: support direct rule evaluation
  api/v1alpha1/awsvalidator_types.go
  go.mod
  go.sum
  internal/controller/awsvalidator_controller.go
  internal/controller/awsvalidator_controller_test.go
  pkg/aws/aws.go
  pkg/constants/constants.go
  pkg/validate/validate.go
  pkg/validators/ami/ami_validator.go
  pkg/validators/ami/ami_validator_test.go
  pkg/validators/common.go
  pkg/validators/iam/iam_validator.go
  pkg/validators/iam/iam_validator_test.go
  pkg/validators/servicequota/servicequota_validator.go
  pkg/validators/servicequota/servicequota_validator_test.go
  pkg/validators/servicequota/usage.go
  pkg/validators/servicequota/usage_test.go
  pkg/validators/tag/tag_validator.go
  pkg/validators/tag/tag_validator_test.go
Labels: enhancement, size:L

#447 chore(main): release 0.1.3
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:S

#457 chore: satisfy ValidationRule
  api/v1alpha1/awsvalidator_types.go
  go.mod
  go.sum
Labels: size:XS

#453 chore(main): release 0.1.4
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:S, lgtm

#462 chore(main): release 0.1.4
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:S, lgtm

#473 refactor: make each rule implement `validationrule.Interface`
  api/v1alpha1/awsvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/awsvalidator_controller_test.go
  pkg/validate/validate.go
  pkg/validators/ami/ami_validator.go
  pkg/validators/ami/ami_validator_test.go
  pkg/validators/servicequota/servicequota_validator.go
  pkg/validators/servicequota/servicequota_validator_test.go
  pkg/validators/tag/tag_validator.go
  pkg/validators/tag/tag_validator_test.go
Labels: enhancement, size:L, lgtm

#468 chore(main): release 0.1.5
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: documentation, autorelease: pending, size:S

#476 fix: embedding structs related to `validationrule.Interface`
  api/v1alpha1/awsvalidator_types.go
Labels: bug, size:S

#474 chore: assert that PluginSpec is implemented
  api/v1alpha1/awsvalidator_types.go
  go.mod
  go.sum
Labels: size:XS, lgtm

#478 chore(main): release 0.1.6
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: bug, autorelease: pending, size:S

#481 fix: YAML rendering of structs embedded in rules
  api/v1alpha1/awsvalidator_types.go
Labels: bug, size:S

#479 chore(main): release 0.1.7
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-aws/Chart.yaml
  chart/validator-plugin-aws/README.md
  chart/validator-plugin-aws/values.yaml
Labels: autorelease: pending, size:S
